name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "oss-sonatype-snapshot-old", "name": "oss-sonatype-snapshot-old", "url": "https://oss.sonatype.org/content/repositories/snapshots/", "releases": { "enabled": "false" }, "snapshots": { "enabled": "true" } },{ "id": "oss-sonatype-snapshot", "name": "oss-sonatype-snapshot", "url": "https://s01.oss.sonatype.org/content/repositories/snapshots/", "releases": { "enabled": "false" }, "snapshots": { "enabled": "true" } }]'
    - name: Build with Maven
      run: mvn -B -U clean package
